### ISSUE TITLE
Incorrect classification

### ISSUE THREAD

**Issue by deleepa** [rifhanakram/sinhala-sentiment-analyser#2]
If I'm not mistaken, this sentence should be classified as negative isn't it?

'ඔබ හරි නපුරු  ළමයෙක්, සමාවෙන්න මම විහිළුවක් කළේ '

**Comment by rifhanakram** [comment]
That's right, as mentioned it has issues with regards to studying the context since the training data set for each class is very less the issue will arise. If there is any room for improvement just bump a PR 

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.6.37&pv=6.0.1&source=email_footer_2] On Mon, Sep 12, 2016 at 11:26 AM, Deleepa < notifications@github.com [notifications@github.com] > wrote:
If I'm not mistaken, this sentence should be classified as negative isn't it?

'ඔබ හරි නපුරු ළමයෙක්, සමාවෙන්න මම විහිළුවක් කළේ '

—

**Comment by deleepa** [comment]
Did you read about the theory behind tf-idf? I found a good article on it. 

http://blog.christianperone.com/2011/09/machine-learning-text-feature-extraction-tf-idf-part-i/

It seems that it should build a vocabulary from the training data. I'm trying to see if I can print that out. If so we can see what's going on underneath the algorithm.

**Comment by rifhanakram** [comment]
@deleepa  Yep i did thats what happens in the vectorizing process, awesome keep me posted on the progress, if i'm correct we can handle the vectorizing process(feature extraction and ignoring stop words) utilizing the numpy library.. btw good read.

**Comment by murzeus** [comment]
I don't think this as an issue anymore, this will have less impact to the output as the training data set grows. Possible solution would be to improve the training data set. Let's close this one if everyone is on the same page with me.

**Comment by singhabahu** [comment]
I don't think this as an issue anymore, this will have less impact on the output as the training data set grows. Possible solution would be to improve the training data set. Let's close this one if everyone is on the same page with me.

**Comment by rifhanakram** [comment]
Yes we can agree on that
